

# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get the Numbers
      id: get_coverage
      run: |
        COVERAGE=40
        if [ $COVERAGE -lt 70 ]; then
          COLOR=red
        elif [ $COVERAGE -lt 90 ]; then
          COLOR=orange
        else
          COLOR=green
        fi
        echo "::set-output name=COVERAGE::$COVERAGE"
        echo "::set-output name=COLOR::$COLOR"
        
            
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
<<<<<<< Updated upstream
=======
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Tests
      id: get_coverage
      run: |
        COVERAGE=$(sed -nE 's/^.*<td>Total<([^>]+>){4}([^<]*).*$/\2/p' target/site/jacoco/index.html | sed -nE 's/[^0-9]*([0-9]+).*/\1/p')
        if [ $COVERAGE -lt 70 ]; then
          COLOR=red
        elif [ $COVERAGE -lt 90 ]; then
          COLOR=orange
        else
          COLOR=green
        fi
        echo "::set-output name=COVERAGE::$COVERAGE"
        echo "::set-output name=COLOR::$COLOR"
        
            
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
>>>>>>> Stashed changes
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 73adb891918b248bf5cd39afb416ee7c
        filename: test.json
        label: Coverage
        message: ${{ steps.get_coverage.outputs.COVERAGE }}%
        color: ${{ steps.get_coverage.outputs.COLOR }}